/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package hotel;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF8yUIlXBzNV8k= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF8yUIlXBzNV8k= >>
// ----------- >>
public class Cliente {
    // ----------- << attribute.annotations@AAAAAAF8yUMESBz8diU= >>
    // ----------- >>
    private int id;

    // ----------- << attribute.annotations@AAAAAAF8yUNAsR0D5Jw= >>
    // ----------- >>
    private String nombre;

    // ----------- << attribute.annotations@AAAAAAF8yUNilR0KuxQ= >>
    // ----------- >>
    private String telefono;

    // ----------- << attribute.annotations@AAAAAAF8yUOLfB0Rk2M= >>
    // ----------- >>
    private String email;

    public int getId() {
        return id;
    }

    public String getNombre() {
        return nombre;
    }

    public String getTelefono() {
        return telefono;
    }

    public String getEmail() {
        return email;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    // ----------- << method.annotations@AAAAAAF8yUQEYx0hq2k= >>
    // ----------- >>
    public void altaCliente() {
    // ----------- << method.body@AAAAAAF8yUQEYx0hq2k= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF8yUQ+2h0oceY= >>
    // ----------- >>
    public void bajaCliente() {
    // ----------- << method.body@AAAAAAF8yUQ+2h0oceY= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF8yURkKB0vwx4= >>
    // ----------- >>
    public void historial() {
    // ----------- << method.body@AAAAAAF8yURkKB0vwx4= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF8yUIlXBzNV8k= >>
// ----------- >>
}