/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package hotel;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF8yUS7Ix03b+0= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF8yUS7Ix03b+0= >>
// ----------- >>
public class Habitacion {
    // ----------- << attribute.annotations@AAAAAAF8yUUx0x1isE0= >>
    // ----------- >>
    private int id;

    // ----------- << attribute.annotations@AAAAAAF8yUVh1B1pWjM= >>
    // ----------- >>
    private boolean estatus;

    // ----------- << attribute.annotations@AAAAAAF8yUV/Eh1wol4= >>
    // ----------- >>
    private String tipo;

    public int getId() {
        return id;
    }

    public boolean isEstatus() {
        return estatus;
    }

    public String getTipo() {
        return tipo;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setEstatus(boolean estatus) {
        this.estatus = estatus;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    // ----------- << method.annotations@AAAAAAF8yUWhQx13dcM= >>
    // ----------- >>
    public void disponibilidad() {
    // ----------- << method.body@AAAAAAF8yUWhQx13dcM= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF8yUXkUR1+GB0= >>
    // ----------- >>
    public void crudHabitacion() {
    // ----------- << method.body@AAAAAAF8yUXkUR1+GB0= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF8yUS7Ix03b+0= >>
// ----------- >>
}