/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package hotel;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF8yUmJQB32hWg= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF8yUmJQB32hWg= >>
// ----------- >>
public class Precio {
    // ----------- << attribute.annotations@AAAAAAF8yUmahx4geZU= >>
    // ----------- >>
    private int tipoHabitacion;

    // ----------- << attribute.annotations@AAAAAAF8yUm/3R4nCSU= >>
    // ----------- >>
    private double costo;

    public int getTipoHabitacion() {
        return tipoHabitacion;
    }

    public double getCosto() {
        return costo;
    }

    public void setTipoHabitacion(int tipoHabitacion) {
        this.tipoHabitacion = tipoHabitacion;
    }

    public void setCosto(double costo) {
        this.costo = costo;
    }

    // ----------- << method.annotations@AAAAAAF8yUopIh43+f4= >>
    // ----------- >>
    public void calcular() {
    // ----------- << method.body@AAAAAAF8yUopIh43+f4= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF8yUpQ4R4+f84= >>
    // ----------- >>
    public void modificarCosto() {
    // ----------- << method.body@AAAAAAF8yUpQ4R4+f84= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF8yUmJQB32hWg= >>
// ----------- >>
}