/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package hotel;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF8yUceAR2F9cc= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF8yUceAR2F9cc= >>
// ----------- >>
public class Reservacion {
    // ----------- << attribute.annotations@AAAAAAF8yUdPBh2vlj8= >>
    // ----------- >>
    private int id;

    // ----------- << attribute.annotations@AAAAAAF8yUdo0R22AUo= >>
    // ----------- >>
    private int id_cliente;

    // ----------- << attribute.annotations@AAAAAAF8yUeN5R29qjM= >>
    // ----------- >>
    private int id_habitacion;

    // ----------- << attribute.annotations@AAAAAAF8yUejeB3EKPI= >>
    // ----------- >>
    private String fechaReserva;

    // ----------- << attribute.annotations@AAAAAAF8yUfDIx3L8GU= >>
    // ----------- >>
    private String fechaLiberacion;

    // ----------- << attribute.annotations@AAAAAAF8yUgG0h3SOig= >>
    // ----------- >>
    private double costo;

    // ----------- << attribute.annotations@AAAAAAF8yUrEGh5HuYs= >>
    // ----------- >>
    private void Attribute1;

    public int getId() {
        return id;
    }

    public int getId_cliente() {
        return id_cliente;
    }

    public int getId_habitacion() {
        return id_habitacion;
    }

    public String getFechaReserva() {
        return fechaReserva;
    }

    public String getFechaLiberacion() {
        return fechaLiberacion;
    }

    public double getCosto() {
        return costo;
    }

    public void getAttribute1() {
        return Attribute1;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setId_cliente(int id_cliente) {
        this.id_cliente = id_cliente;
    }

    public void setId_habitacion(int id_habitacion) {
        this.id_habitacion = id_habitacion;
    }

    public void setFechaReserva(String fechaReserva) {
        this.fechaReserva = fechaReserva;
    }

    public void setFechaLiberacion(String fechaLiberacion) {
        this.fechaLiberacion = fechaLiberacion;
    }

    public void setCosto(double costo) {
        this.costo = costo;
    }

    public void setAttribute1(void Attribute1) {
        this.Attribute1 = Attribute1;
    }

    // ----------- << method.annotations@AAAAAAF8yUhAMh3Z/RM= >>
    // ----------- >>
    public void crear() {
    // ----------- << method.body@AAAAAAF8yUhAMh3Z/RM= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF8yUifOh3g7AE= >>
    // ----------- >>
    public void cobrar() {
    // ----------- << method.body@AAAAAAF8yUifOh3g7AE= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF8yUjEEx3nWu0= >>
    // ----------- >>
    public void cancelar() {
    // ----------- << method.body@AAAAAAF8yUjEEx3nWu0= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF8yUkCdR3uUIc= >>
    // ----------- >>
    public void asignacion() {
    // ----------- << method.body@AAAAAAF8yUkCdR3uUIc= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF8yUskRR5OokU= >>
    // ----------- >>
    public void aplicarDescuento() {
    // ----------- << method.body@AAAAAAF8yUskRR5OokU= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF8yUceAR2F9cc= >>
// ----------- >>
}